#kubernetes 
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: disckup
  name: disckup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: disckup
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: disckup
    spec:
      containers:
        - name: disckup
          image: senseupdevcrapps.azurecr.io/bots/disckup:latest
          envFrom:
            - configMapRef:
                name: disckup-config
      restartPolicy: Always
      serviceAccountName: default
